/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kakurasu;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import javax.swing.GroupLayout.ParallelGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.WindowConstants;

/**
 *
 * @author matjazsu
 */
public class Window extends javax.swing.JFrame {
    
    private JPanel m_JPanel;
    
    private int m_rows=7;
    private int m_cols=7;
    
    //Solutions  
    private Solutions m_SolutionsHelper;
    private String[][] m_Solutions;
            
    //Game field
    private Field[][] m_Fields;
    
    //Total number of correct choices
    private int m_Total = 0;    
    //Current number of correct choices
    private int m_Current = 0;
    
    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
        m_SolutionsHelper = new Solutions();
        initGamingField();
        this.setTitle("Kakurasu");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanGameField = new javax.swing.JPanel();
        jMenu = new javax.swing.JMenuBar();
        jGame = new javax.swing.JMenu();
        jNewGame = new javax.swing.JMenuItem();
        jClose = new javax.swing.JMenuItem();
        jHelp = new javax.swing.JMenu();
        jShowSolution = new javax.swing.JMenuItem();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout jPanGameFieldLayout = new javax.swing.GroupLayout(jPanGameField);
        jPanGameField.setLayout(jPanGameFieldLayout);
        jPanGameFieldLayout.setHorizontalGroup(
            jPanGameFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );
        jPanGameFieldLayout.setVerticalGroup(
            jPanGameFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );

        jGame.setText("Game");

        jNewGame.setText("New game");
        jNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNewGameActionPerformed(evt);
            }
        });
        jGame.add(jNewGame);

        jClose.setText("Exit");
        jClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCloseActionPerformed(evt);
            }
        });
        jGame.add(jClose);

        jMenu.add(jGame);

        jHelp.setText("Help");

        jShowSolution.setText("Show solution");
        jShowSolution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShowSolutionActionPerformed(evt);
            }
        });
        jHelp.add(jShowSolution);

        jMenu.add(jHelp);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanGameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanGameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jCloseActionPerformed

    private void jShowSolutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShowSolutionActionPerformed
        // TODO add your handling code here:
        showSolution(false);
    }//GEN-LAST:event_jShowSolutionActionPerformed

    private void jNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNewGameActionPerformed
        // TODO add your handling code here:
        initGamingField();
    }//GEN-LAST:event_jNewGameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }
    
    private void initGamingField(){
        this.jPanGameField.removeAll();
        this.jPanGameField.repaint();
        this.m_Solutions = this.m_SolutionsHelper.getRandomSolution();
        this.m_Fields = new Field[this.m_Solutions.length][this.m_Solutions[0].length];
        this.m_Total = getTotalNumberFromSolutions();
        this.m_Current = 0;
        
        int xPos = 0;
        int yPos = 0;
        int width = 0;
        for(int i = 0; i < m_Fields.length; i++){                     
            for(int j = 0; j < m_Fields[0].length; j++){
                if(i==0 || i==m_Fields.length-1 || j==0 || j==m_Fields[0].length-1){
                    Field field = new Field();
                    field.f_button = new javax.swing.JButton();
                    field.f_button.setText(this.m_Solutions[i][j]);
                    field.f_button.setEnabled(false);
                    field.f_button.setVisible(true);
                    field.f_button.setSize(50, 50);
                    field.f_button.setLocation(xPos,yPos);

                    this.m_Fields[i][j] = field;
                    this.jPanGameField.add(field.f_button);
                    xPos = xPos + field.f_button.getWidth();
                }
                else{
                    Field field = new Field();
                    field.f_isBlue = this.m_Solutions[i][j] == "B"; //TODO: get info about
                    field.f_gameField = true;
                    field.f_button = new javax.swing.JButton();
                    field.f_button.setText("");
                    field.f_button.setVisible(true);
                    field.f_button.setSize(50, 50);
                    field.f_button.setLocation(xPos,yPos);
                    field.f_button.setName(String.valueOf(i) + "," + String.valueOf(j));
                    field.f_button.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            f_buttonActionPerformed(evt);
                        }
                    });

                    this.m_Fields[i][j] = field;
                    this.jPanGameField.add(field.f_button);
                    xPos = xPos + field.f_button.getWidth();
                }  
            }
            width = xPos;
            xPos = 0;
            yPos = yPos + this.m_Fields[i][0].f_button.getHeight();
        }   
        
        this.jPanGameField.setPreferredSize(new Dimension(width, yPos));
        this.jPanGameField.revalidate();
        this.setSize(width+6, yPos+52);
    }
    
    private int getTotalNumberFromSolutions(){
        int total = 0;        
        for(int i = 0; i < m_Solutions.length; i++){                     
            for(int j = 0; j < m_Solutions[0].length; j++){
                if(m_Solutions[i][j] == "B"){
                    total++;
                }
            }
        }
        return total;
    }

    private void f_buttonActionPerformed(java.awt.event.ActionEvent evt){
        JButton btn = (JButton)evt.getSource();
        int i = Integer.parseInt(btn.getName().split(",")[0]);        
        int j = Integer.parseInt(btn.getName().split(",")[1]);        
        Field field = this.m_Fields[i][j];     
        
        if(field.f_isBlue){
            btn.setBackground(Color.BLUE);
            this.m_Current++;
            if(this.m_Current == this.m_Total){
                JOptionPane.showMessageDialog(this, "You won!", "Kakurasu", WIDTH);
                showSolution(true);
            }
        }
        else{
            btn.setText("X");
            btn.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "You lost!", "Kakurasu", WIDTH);
            showSolution(false);
        }
    }
    
    private void showSolution(Boolean won){
        for(int i = 0; i < m_Fields.length ; i++){                     
            for(int j = 0; j < m_Fields[0].length; j++){
                if(m_Fields[i][j].f_isBlue){
                    m_Fields[i][j].f_button.setBackground(Color.BLUE);
                }
                else if(m_Fields[i][j].f_gameField){
                    m_Fields[i][j].f_button.setText("X");
                }
                else{
                    if(won){
                        m_Fields[i][j].f_button.setBackground(Color.green);
                    }                   
                }
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jClose;
    private javax.swing.JMenu jGame;
    private javax.swing.JMenu jHelp;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JMenuItem jNewGame;
    private javax.swing.JPanel jPanGameField;
    private javax.swing.JMenuItem jShowSolution;
    // End of variables declaration//GEN-END:variables
}
